# Generated by Django 3.1.5 on 2021-01-31 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=25)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('vendor', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('type', models.ForeignKey(default='-', on_delete=django.db.models.deletion.SET_DEFAULT, to='expenditures.type')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
