# Generated by Django 3.1.5 on 2021-01-31 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenditures', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='ExpenditureType',
        ),
    ]
