# Generated by Django 3.1.5 on 2021-01-31 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='debt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='debt.debt'),
            preserve_default=False,
        ),
    ]
